# This action will determine if the current branch that triggered this action has a PR open.
# Useful to generate comments on a PR with output values of a deployed testing environment, for example.

# Example of usage:
# is-in-pr:
#   name: Is branch in PR
#   permissions:
#     pull-requests: read
#   uses: ./.github/workflows/is-in-pr.yml

# The output can be used like:
# add-pull-request-comment:
#   if: needs.is-in-pr.outputs.is-in-pr == 'true'
#   needs: [is-in-pr]

name: Is branch in PR?

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: "ubuntu-latest"
        description: "The hosted runner"
    outputs:
      is-in-pr:
        description: True if the branch is in PR
        value: ${{ jobs.run.outputs.is-in-pr }}
      pr-number:
        description: The PR's number
        value: ${{ jobs.run.outputs.pr-number }}

permissions:
  pull-requests: read

jobs:
  run:
    runs-on: ${{ inputs.runs-on }}
    outputs:
      is-in-pr: ${{ steps.output-pr-result.outputs.is-in-pr }}
      pr-number: ${{ steps.output-pr-result.outputs.pr-number }}
    steps:
      - name: Find Pull Request
        uses: juliangruber/find-pull-request-action@v1
        id: find-pull-request
        with:
          branch: ${{ github.ref_name }}
      - run: |
          echo "is-in-pr=${{ steps.find-pull-request.outputs.number != '' }}" >> $GITHUB_OUTPUT
          echo "pr-number=${{ steps.find-pull-request.outputs.number }}" >> $GITHUB_OUTPUT
        id: output-pr-result
