# This is a full example using the sample client GitHub Actions.
# This action is to be triggered manually and would deploy a frontend and JavaScript/TypeScript API to Azure Static Web Apps.
# This will require an active Azure Static Web App environment and a secret added to your repo called "AZURE_STATIC_WEB_APPS_API_TOKEN_DEV"
# containing the relevant Static Web App Token.

# Note: The frontend directory does not contain the "is-in-pr.yml" workflow. This can be located in the "other" directory.
# Note: The frontend directory does not contain the "javascript-build-api.yml" workflow. This can be located in the "backend/javascript" directory.

name: "Deploy Static Web Apps"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to manually deploy to"
        type: choice
        required: true
        options:
          - "fte"

# This will prevent two jobs spinning up at once.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  es-lint:
    name: ES Lint
    uses: ./.github/workflows/client-lint.yml

  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/client-unit-test.yml

  # Build the client but not for every push to the repo
  # This will prevent over-usage of the build runners.
  build-client:
    name: Build Client
    needs: [unit-tests, es-lint]
    uses: ./.github/workflows/client-build.yml

  # This action is not found in this directory but can be found in the "./other" GitHub Actions directory.
  is-in-pr:
    name: Is branch in PR
    permissions:
      pull-requests: read
    uses: ./.github/workflows/is-in-pr.yml

  # call the API build module
  # This could be excluded if not needed.
  build-api:
    name: Build API
    uses: ./.github/workflows/javascript-build-api.yml

  deploy-job-fte:
    if: github.event_name == 'workflow_dispatch' && inputs.environment == 'fte'
    uses: ./.github/workflows/deploy-static-web-app.yml
    needs: [build-client, build-api]
    with:
      production-branch: "main"
      deployment-environment: ${{ inputs.environment }}
      development-environment-deploy: true
    secrets:
      azure-static-web-apps-api-token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}

  # This action could also trigger the Lighthouse action, if it is included in your repo.
  paint-pull-request:
    if: needs.is-in-pr.outputs.is-in-pr == 'true'
    needs: [build-client, build-api, is-in-pr, deploy-job-fte]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add comment to PR
        uses: marocchino/sticky-pull-request-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ needs.is-in-pr.outputs.pr-number }}
          header: staticwebapp
          message: |
            👋 This has been deployed to FTE: ${{ needs.deploy-job-fte.outputs.static-web-app-url }}
