# This is an example of the dotnet workflows and how they could be used in your application.

name: "Framework Pipeline"

on:
  push:
    paths-ignore:
      - "Documentation/**"
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  version:
    name: Version Number
    runs-on: windows-latest
    outputs:
      git-version: ${{ steps.gitversion.outputs.nuGetVersionV2 }}
      major-minor-patch: ${{ steps.gitversion.outputs.majorMinorPatch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: "5.5.0"
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15
        with:
          useConfigFile: true

  print-git-version:
    name: GitVersion - ${{ needs.version.outputs.git-version }}
    runs-on: ubuntu-latest
    needs: [version]
    steps:
      - run: echo ${{ needs.version.outputs.git-version }}

  unit-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: (${{ matrix.os }}) Unit Tests ${{ needs.version.outputs.git-version }}
    uses: ./.github/workflows/dotnet-tests.yml
    needs: [version]
    with:
      path: _Tests/Tests/UnitTests/_Tests.Tests.UnitTests.csproj
      dotnet-version: "6.0.401"
      type: "unit"
      git-version: ${{ needs.version.outputs.git-version }}
      runs-on: ${{ matrix.os }}

  integration-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: (${{ matrix.os }}) Integration Tests ${{ needs.version.outputs.git-version }}
    uses: ./.github/workflows/dotnet-tests.yml
    needs: [version]
    with:
      path: _Tests/Tests/IntegrationTests/_Tests.Tests.IntegrationTests.csproj
      dotnet-version: "6.0.401"
      type: "integration"
      git-version: ${{ needs.version.outputs.git-version }}
      runs-on: ${{ matrix.os }}

  build:
    name: Build .NET ${{ needs.version.outputs.git-version }}
    uses: ./.github/workflows/dotnet-build.yml
    needs: [unit-tests, integration-tests, version]
    with:
      artifact-name: ReplaceThis-ReplaceThis-${{ needs.version.outputs.git-version }}
      dotnet-version: "6.0.401"
      package-version: ${{ needs.version.outputs.git-version }}
      version: ${{ needs.version.outputs.major-minor-patch }}
      package-release-notes: "Built from commit ${{ github.sha }}"
      solution-path: "ReplaceThis.ReplaceThisToo.sln"

  release:
    name: Release .NET ${{ needs.version.outputs.git-version }}
    runs-on: windows-latest
    needs: [unit-tests, integration-tests, version, build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Retrieve Release Artifact
        uses: actions/download-artifact@v3
        with:
          name: ReplaceThis-ReplaceThis-${{ needs.version.outputs.git-version }}
          path: _nupkg
      - name: Generate Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: _nupkg/*
          body_path: ReleaseNotes.md
